dist: xenial
language: python

env:
  global:
    - >
      PATH=$HOME/.poetry/bin:$PATH
      POETRYINSTALLOPTS=-v
      FLAKE8OPTS=-v
      PYTESTOPTS=-v

matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.8"
      env: TOXENV=flake8

install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - -- --version 1.0.5
  - pip install tox
  - if [[ $TOXENV == *py* ]]; then pip install coveralls; fi

script:
  - tox

after_success:
  - if [[ $TOXENV == *py* ]]; then coveralls; fi
