language: python

# Run on container-based infrastructure
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  include:
    - env: RUN_FLAKE8=1
      python: "3.5"

install:
  - make ci_init

script:
  - make ci_script

after_success:
  - make ci_after
